# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_enricher_wrappers", use_symbols = TRUE, package_name = "enricher")

#' @usage NULL
#' @useDynLib enricher, .registration = TRUE
NULL


# nolint end
